// Generates src/cities.js from Natural Earth's populated places (public domain). Runs as part of
// the build, so the page itself never fetches anything; the release is pinned for reproducible output.
// With --if-missing it only runs when the file doesn't exist yet (for dev and tests).
import { existsSync, writeFileSync } from 'node:fs';
import world from 'world-atlas/countries-50m.json' with { type: 'json' };
import { COUNTRIES } from '../src/countries.js';
import { countryRegion, projectionFor } from '../src/geo.js';

const SOURCE =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_10m_populated_places_simple.geojson';
const PER_COUNTRY = 12;
// Natural Earth lists some suburbs as separate cities (Benoni next to Johannesburg). Cities this
// close (relative to the country's size) are also hard to tell apart on the map, so keep only one.
const MIN_SEPARATION = 0.04;
const MIN_SEPARATION_KM = 20;

// Natural Earth has typos, local spellings and outdated names; use what players would recognize.
const RENAMES = {
  'At Taif': 'Taif',
  'Bur Said': 'Port Said',
  'Dund-Us': 'Khovd',
  'Göteborg': 'Gothenburg',
  Hania: 'Chania',
  Ioanina: 'Ioannina',
  Iraklio: 'Heraklion',
  Icel: 'Mersin',
  'Kitakyūshū': 'Kitakyushu',
  Khmelnytskyy: 'Khmelnytskyi',
  'Kryvyy Rih': 'Kryvyi Rih',
  'Kōbe': 'Kobe',
  'København': 'Copenhagen',
  'La Coruña': 'A Coruña',
  Makkah: 'Mecca',
  Muineachan: 'Monaghan',
  'Nur-Sultan': 'Astana',
  Olgiy: 'Ölgii',
  Oostanay: 'Kostanay',
  'Ōsaka': 'Osaka',
  Patra: 'Patras',
  'Pinar del Rio': 'Pinar del Río',
  Pizen: 'Plzeň',
  Puttalan: 'Puttalam',
  Qaraghandy: 'Karaganda',
  Rostov: 'Rostov-on-Don',
  Shenyeng: 'Shenyang',
  Songnam: 'Seongnam',
  Suchboatar: 'Sükhbaatar',
  'Usti Nad Labem': 'Ústí nad Labem',
  Xian: "Xi'an",
  Zaporizhzhya: 'Zaporizhzhia',
  'Århus': 'Aarhus',
};
// Obscure or suburban entries that Natural Earth's population figures rank too high.
const EXCLUDED = new Set(['Bærum', 'Cranbourne', 'Hechi', 'Ikare', 'Al Hillah', 'Manukau', 'Waitakere', 'Southend-on-Sea']);

const OUTPUT = new URL('../src/cities.js', import.meta.url);
if (process.argv.includes('--if-missing') && existsSync(OUTPUT)) process.exit(0);

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`Fetching ${SOURCE} failed: ${response.status}`);
const places = (await response.json()).features.map((f) => f.properties);

const cities = {};
for (const { name } of COUNTRIES) {
  // Only cities that appear on the country's map, not in overseas territories (Honolulu, Cayenne).
  const region = countryRegion(world, name);
  const projection = projectionFor(region);
  const [[x0, y0], [x1, y1]] = boundsOf(region, projection);
  const onMap = (p) => {
    const [x, y] = projection([p.longitude, p.latitude]);
    return x >= x0 && x <= x1 && y >= y0 && y <= y1;
  };

  const minKm = Math.max(MIN_SEPARATION_KM, MIN_SEPARATION * region.sizeKm);
  const candidates = places
    .filter((p) => p.adm0name === name && onMap(p) && !EXCLUDED.has(cleanName(p)))
    // Capitals first, so they are never dropped for being close to a bigger city (Pretoria, Bern).
    .sort((a, b) => isCapital(b) - isCapital(a) || b.pop_max - a.pop_max);

  const chosen = [];
  for (const p of candidates) {
    if (chosen.some((c) => distanceKm(c, p) < minKm)) continue;
    chosen.push(p);
    if (chosen.length === PER_COUNTRY) break;
  }
  if (chosen.length < 3) throw new Error(`Only ${chosen.length} cities found for ${name}`);
  cities[name] = chosen.map((p) => ({
    name: RENAMES[cleanName(p)] ?? cleanName(p),
    lon: round(p.longitude),
    lat: round(p.latitude),
  }));
}

const lines = Object.entries(cities).map(
  ([country, list]) =>
    `  ${JSON.stringify(country)}: [\n${list.map((c) => `    ${JSON.stringify(c)},`).join('\n')}\n  ],`,
);
writeFileSync(
  OUTPUT,
  `// Generated by scripts/build-cities.mjs from Natural Earth populated places. Do not edit by hand.\nexport const CITIES = {\n${lines.join('\n')}\n};\n`,
);
console.log(`Wrote ${Object.values(cities).flat().length} cities for ${COUNTRIES.length} countries`);

// Some names contain doubled spaces or invisible direction marks.
function cleanName(p) {
  return p.name.replace(/[\u200e\u200f]/g, '').replace(/\s+/g, ' ').trim();
}

function isCapital(p) {
  return p.featurecla === 'Admin-0 capital' ? 1 : 0;
}

function boundsOf(region, projection) {
  const points = region.geometry.coordinates.flat(2).map((p) => projection(p));
  const xs = points.map((p) => p[0]);
  const ys = points.map((p) => p[1]);
  return [
    [Math.min(...xs), Math.min(...ys)],
    [Math.max(...xs), Math.max(...ys)],
  ];
}

function distanceKm(a, b) {
  const rad = Math.PI / 180;
  const dLat = (b.latitude - a.latitude) * rad;
  const dLon = (b.longitude - a.longitude) * rad;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(a.latitude * rad) * Math.cos(b.latitude * rad) * Math.sin(dLon / 2) ** 2;
  return 2 * 6371 * Math.asin(Math.sqrt(h));
}

function round(v) {
  return Math.round(v * 1000) / 1000;
}
