title: fusectore.dev
email: ody@fusectore.dev
description: >-
  My blog on programming.
baseurl: ""
domain: "fusectore.dev"
url: "https://fusectore.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rethab

permalink: /:year/:month/:day/:title:output_ext

theme: minima
plugins:
  - jekyll-feed
