title: fusectore.dev
email: ody@fusectore.dev
description: >-
  My blog on programming.
baseurl: ""
domain: "fusectore.dev"
url: "https://fusectore.dev"
github_username: rethab

permalink: /:year/:month/:day/:title:output_ext

exclude:
  - "*.iml"
  - ".idea"
  - ".github"
  - "vendor"

theme: minima
plugins:
  - jekyll-feed
