// Compiles wasm/breed.wat into breed-wasm.js, a classic script that
// embeds the module as base64. The app is opened from file://, where it cannot
// fetch a .wasm file, so the bytes have to ship inside a script.
const fs = require('node:fs');
const path = require('node:path');

const SOURCE = path.join(__dirname, '../wasm/breed.wat');
const OUTPUT = path.join(__dirname, '../breed-wasm.js');

async function compile() {
  const wabt = await require('wabt')();
  const module = wabt.parseWat(SOURCE, fs.readFileSync(SOURCE, 'utf8'), { simd: true });
  try {
    module.validate();
    return Buffer.from(module.toBinary({}).buffer);
  } finally {
    module.destroy();
  }
}

function render(bytes) {
  return `// Generated by scripts/build-wasm.js from wasm/breed.wat. Do not edit.
(function () {
  const base64 = '${bytes.toString('base64')}';
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = base64;
  }
  globalThis.BREED_WASM = base64;
})();
`;
}

if (require.main === module) {
  compile().then((bytes) => {
    fs.writeFileSync(OUTPUT, render(bytes));
    console.log(`${path.relative(process.cwd(), OUTPUT)}: ${bytes.length} bytes`);
  });
}

module.exports = { compile, render, OUTPUT };
