// `name` must match `properties.name` in world-atlas. Only the largest landmass is scored,
// so countries where that isn't obvious get a hint.
export const COUNTRIES = [
  { label: 'Argentina', name: 'Argentina' },
  { label: 'Australia', name: 'Australia', hint: 'mainland, without Tasmania' },
  { label: 'Austria', name: 'Austria' },
  { label: 'Brazil', name: 'Brazil' },
  { label: 'Canada', name: 'Canada', hint: 'mainland, without the Arctic islands' },
  { label: 'Chile', name: 'Chile' },
  { label: 'China', name: 'China', hint: 'without Hainan' },
  { label: 'Colombia', name: 'Colombia' },
  { label: 'Cuba', name: 'Cuba' },
  { label: 'Czechia', name: 'Czechia' },
  { label: 'Denmark', name: 'Denmark', hint: 'Jutland only' },
  { label: 'Egypt', name: 'Egypt' },
  { label: 'Finland', name: 'Finland' },
  { label: 'France', name: 'France', hint: 'mainland, without Corsica' },
  { label: 'Germany', name: 'Germany' },
  { label: 'Greece', name: 'Greece', hint: 'mainland, without the islands' },
  { label: 'Iceland', name: 'Iceland' },
  { label: 'India', name: 'India' },
  { label: 'Iran', name: 'Iran' },
  { label: 'Ireland', name: 'Ireland' },
  { label: 'Italy', name: 'Italy', hint: 'mainland, without Sicily and Sardinia' },
  { label: 'Japan', name: 'Japan', hint: 'Honshu only' },
  { label: 'Kazakhstan', name: 'Kazakhstan' },
  { label: 'Madagascar', name: 'Madagascar' },
  { label: 'Mexico', name: 'Mexico' },
  { label: 'Mongolia', name: 'Mongolia' },
  { label: 'Netherlands', name: 'Netherlands', hint: 'mainland, without the islands' },
  { label: 'New Zealand', name: 'New Zealand', hint: 'South Island only' },
  { label: 'Nigeria', name: 'Nigeria' },
  { label: 'Norway', name: 'Norway', hint: 'mainland only' },
  { label: 'Peru', name: 'Peru' },
  { label: 'Poland', name: 'Poland' },
  { label: 'Portugal', name: 'Portugal', hint: 'mainland only' },
  { label: 'Russia', name: 'Russia', hint: 'mainland only' },
  { label: 'Saudi Arabia', name: 'Saudi Arabia' },
  { label: 'South Africa', name: 'South Africa' },
  { label: 'South Korea', name: 'South Korea', hint: 'mainland only' },
  { label: 'Spain', name: 'Spain', hint: 'mainland, without the islands' },
  { label: 'Sri Lanka', name: 'Sri Lanka' },
  { label: 'Sweden', name: 'Sweden', hint: 'mainland only' },
  { label: 'Switzerland', name: 'Switzerland' },
  { label: 'Thailand', name: 'Thailand' },
  { label: 'Turkey', name: 'Turkey', hint: 'Anatolia only, without the European part' },
  { label: 'Ukraine', name: 'Ukraine' },
  { label: 'United Kingdom', name: 'United Kingdom', hint: 'Great Britain only' },
  { label: 'United States', name: 'United States of America', hint: 'lower 48 states only' },
  { label: 'Vietnam', name: 'Vietnam' },
];
