on: push

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g markdownlint-cli
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint **/*.markdown --ignore node_modules


